# Generated by Django 5.2.7 on 2025-11-13 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Мова озвучки')),
            ],
            options={
                'verbose_name': 'Мова',
                'verbose_name_plural': 'Мови',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Платформа')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформи',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Відеогра')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка')),
                ('stock', models.PositiveIntegerField(default=100, verbose_name='Кількість')),
                ('publisher', models.CharField(max_length=255, verbose_name='Видавництво')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('watched', models.PositiveIntegerField(default=0, verbose_name='Перегляди')),
                ('description', models.TextField(default='Тут скоро зʼявиться ваш опис...', verbose_name='Опис гри')),
                ('info', models.TextField(default='Додаткова інформація про продукт', verbose_name='Інформація про гру')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='Опублікований')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gameshop.category', verbose_name='Категорія')),
                ('genres', models.ManyToManyField(blank=True, related_name='games', to='gameshop.genre', verbose_name='Жанр')),
                ('languages_supported', models.ManyToManyField(blank=True, related_name='games', to='gameshop.language', verbose_name='Мова')),
                ('platforms', models.ManyToManyField(blank=True, related_name='games', to='gameshop.platform', verbose_name='Платформа')),
                ('tags', models.ManyToManyField(blank=True, related_name='games', to='gameshop.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Відеогра',
                'verbose_name_plural': 'Відеоігри',
            },
        ),
    ]
