# Generated by Django 5.2.7 on 2025-11-13 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0002_genre_language_platform_tag_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='gameshop.category', verbose_name='Категорія'),
        ),
    ]
