# Generated by Django 5.2.7 on 2025-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0004_alter_game_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', to='gameshop.genre', verbose_name='Жанр'),
        ),
    ]
