# Generated by Django 5.2.7 on 2025-11-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0005_alter_game_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Контактне імʼя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Контактне прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Пошта')),
                ('subject', models.CharField(max_length=150, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення повідомлення')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Стан')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
            },
        ),
    ]
